"""
Integration test: Swarm -> Hunter -> (ledger) -> Weaver -> Dossier.

Proves that findings generated by real analysis modules actually survive
the full round-trip into a signed, human-readable final report -- not
just that each module's own ledger entries look right in isolation
(already covered by unit tests), but that the NARRATIVE GENERATION layer
correctly surfaces what the analysis layer found.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))


@pytest.fixture
def chain(isolated_stamp, tmp_path, monkeypatch):
    from yomi_engine import dossier as dossier_module
    from yomi_engine import hunter as hunter_module
    from yomi_engine import swarm as swarm_module

    fake_swarm_dir = tmp_path / "fake_pkg" / "yomi_engine"
    fake_dossier_dir = tmp_path / "fake_pkg2" / "yomi_engine"
    fake_swarm_dir.mkdir(parents=True)
    fake_dossier_dir.mkdir(parents=True)
    monkeypatch.setattr(swarm_module, "__file__", str(fake_swarm_dir / "swarm.py"))
    monkeypatch.setattr(dossier_module, "__file__", str(fake_dossier_dir / "dossier.py"))
    monkeypatch.setattr("shutil.which", lambda name: None)
    monkeypatch.setenv("YOMI_FORENSIC_PATH", str(tmp_path))

    return {
        "swarm": swarm_module.SwarmOrchestrator(),
        "hunter": hunter_module.OmniVectorHunter(),
        "dossier": dossier_module.CourtReadyDossier(),
    }


def test_swarm_findings_survive_into_final_dossier(chain, isolated_stamp):
    """
    Runs a real (tool-unavailable, but real-code-path) swarm scan and a
    real hunt, then generates a dossier from whatever the ledger actually
    accumulated -- confirming the SWARM/HUNTER agent names and their
    real action_types show up verbatim in the human-readable narrative,
    proving the ledger->weaver->dossier pipeline doesn't silently drop or
    garble real analysis-layer output.

    NOTE: generate_pdf_dossier() has no return statement (implicit None)
    -- confirmed by reading the source, not assumed. Output is located by
    globbing report_dir, matching the pattern the Fase 3 unit tests
    already established for this module.
    """
    swarm_result = chain["swarm"].deploy_swarm()
    assert swarm_result["status"] == "SWARM_COMPLETE"

    hunt_result = chain["hunter"].hunt_root_cause(999999)
    assert hunt_result["status"] == "HUNT_COMPLETE"

    chain["dossier"].generate_pdf_dossier()

    txt_file = next(Path(chain["dossier"].report_dir).glob("*.txt"))
    txt_content = txt_file.read_text(encoding="utf-8")

    assert "DEPLOYED" in txt_content  # SwarmOrchestrator.deploy_swarm's ledger entry
    assert "ROOT_CAUSE_COMPILED" in txt_content  # OmniVectorHunter.hunt_root_cause's ledger entry


def test_dossier_signature_verifies_against_the_real_generated_content(chain, isolated_stamp):
    """
    End-to-end integrity check across the real signing chain (not mocked):
    generate a real dossier, read back its own signature file, and
    confirm the signature actually corresponds to the real file's real
    current content -- catching any case where signing might happen
    against stale/wrong content due to a file-handle or timing bug in the
    interaction between CourtReadyDossier and its _sign_artifact helper.

    NOTE: the signature payload's field is "signature" (not "sha256" --
    confirmed by reading the source), and its content depends on whether
    an HMAC key was available: HMAC-SHA256 (base64) if isolated_stamp has
    one, plain SHA256 (hex) if not. Verified against whichever mode
    actually applied, matching the same conditional pattern the Fase 3
    unit test (test_sign_artifact_falls_back_to_hmac_or_sha256_without_gpg)
    already established for this module.
    """
    import base64
    import hashlib
    import hmac as hmac_module

    chain["swarm"].deploy_swarm()
    chain["dossier"].generate_pdf_dossier()

    txt_path = next(Path(chain["dossier"].report_dir).glob("*.txt"))
    sig_path = Path(str(txt_path) + ".sig")
    assert sig_path.exists()

    sig_payload = json.loads(sig_path.read_text())
    file_bytes = txt_path.read_bytes()

    if sig_payload["signature_type"] == "HMAC-SHA256":
        assert isolated_stamp.hmac_key, "signed as HMAC but no hmac_key present to verify against"
        expected = base64.b64encode(
            hmac_module.new(isolated_stamp.hmac_key, file_bytes, hashlib.sha256).digest()
        ).decode("ascii")
    else:
        expected = hashlib.sha256(file_bytes).hexdigest()

    assert sig_payload["signature"] == expected
