import time
import json
import os
import sys

# Append root directory to sys.path to ensure absolute imports function correctly
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

from yomi_engine.swarm import SwarmOrchestrator
from yomi_core.router import YomiRouter

# ==============================================================================
# YOMI TRIAGE SYSTEM: Core Module - Infinite Sentinel Loop
# Purpose: Adaptive polling daemon. Operates at extreme efficiency during
#          peacetime, escalates to hyper-scan upon threat detection.
#          Acts as the event-driven trigger for the Zero-Prompt Engine.
# ==============================================================================


class SentinelDaemon:
    def __init__(self):
        self.swarm = SwarmOrchestrator()
        self.router = YomiRouter()
        self.threat_level = "SAFE"  # Operational States: SAFE, ESCALATED, CRITICAL
        self.is_running = False

    def _get_polling_interval(self) -> float:
        """
        Calculates the adaptive polling rate based on current threat conditions.
        Ensures <1% CPU utilization during SAFE state.
        """
        if self.threat_level == "SAFE":
            return 5.0  # Standard Patrol: 5 seconds
        elif self.threat_level == "ESCALATED":
            return 1.0  # Heightened Awareness: 1 second
        else:
            return 0.1  # CRITICAL: Hyper-Scan mode (100ms)

    def _zero_prompt_trigger(self, anomaly_data: list):
        """
        Simulates the Event-Driven Zero-Prompt generation.
        Passes the extracted anomalies to the local LLM routing pipeline.
        """
        print(
            "\n[SENTINEL] [CYBER-PURPLE] Anomaly verified! Engaging Zero-Prompt Engine..."
        )

        # In a production environment, this payload is dynamically generated by OpenClaw/Gemini.
        # For development validation, we simulate the Triad Council's JSON response output.
        simulated_llm_response = {
            "red_agent": f"Identified malicious behavior in findings: {anomaly_data[0]}",
            "blue_agent": "Unverified signature. Requires immediate suspension to prevent lateral movement.",
            "judge_verdict": "Threat threshold met. Execute Cryogenic Freeze.",
            "epistemic_doubt": 5,  # Low doubt ensures it bypasses the Shadow Net and executes
            "action": "freeze",
            "target_pid": 4092,  # Target derived from swarm findings
        }

        # Route the autonomous intent to the Triad Council Gatekeeper
        self.router.evaluate_intent(json.dumps(simulated_llm_response))

    def start(self):
        """
        Initializes the infinite background loop.
        This is the primary heartbeat of the Yomi Triage System.
        """
        self.is_running = True
        print(
            "\n[SENTINEL] [PLASMA BLUE] Infinite Sentinel Loop initialized. Monitoring system state..."
        )
        print("[SENTINEL] Press Ctrl+C to abort daemon.\n")

        try:
            while self.is_running:
                # 1. Deploy the Predator Swarm (Micro-Agents)
                swarm_results = self.swarm.deploy_swarm()
                anomalies = []

                # Parse findings from all active swarm agents
                for report in swarm_results.get("reports", []):
                    findings = report.get("findings", [])
                    if findings:
                        anomalies.extend(findings)

                # 2. Adaptive Polling Logic & Threat Escalation
                if anomalies:
                    if self.threat_level == "SAFE":
                        print(
                            "\n[SENTINEL] [BLOOD RED] Threat detected by Swarm! Escalating to CRITICAL mode."
                        )
                        self.threat_level = "CRITICAL"

                    # Trigger AI analysis autonomously without human keyboard input
                    self._zero_prompt_trigger(anomalies)

                    # Reset to escalated mode to monitor for immediate aftershocks
                    self.threat_level = "ESCALATED"
                else:
                    if self.threat_level != "SAFE":
                        print(
                            "\n[SENTINEL] [PLASMA BLUE] System clear. Returning to SAFE mode baseline."
                        )
                    self.threat_level = "SAFE"

                # 3. Dynamic Sleep (Resource Management)
                time.sleep(self._get_polling_interval())

        except KeyboardInterrupt:
            print(
                "\n[SENTINEL] [VOID BLACK] Sentinel Loop manually terminated by Commander."
            )
            self.is_running = False


# ==============================================================================
# DEVELOPMENT TESTING BLOCK
# ==============================================================================
if __name__ == "__main__":
    sentinel = SentinelDaemon()
    sentinel.start()
